### ISSUE TITLE
Opening undo prefills Telescope with '<cr>'

### ISSUE THREAD

**Issue by gregorias** [debugloop/telescope-undo.nvim#10]
<img width="1622" alt="image" src="https://user-images.githubusercontent.com/722385/208918809-50e8a9e1-cf0b-4903-bb92-2062519d6ef5.png">

When I open the undo extension in Telescope, either via `:Telescope undo` or a keyboard shortcut, the Telescope input field is prefilled with `<cr>`.

Do you know why that might be? I can provide a reproducible environment if that is not something you are aware of.

[Reddit comment with the same question.](https://www.reddit.com/r/neovim/comments/znjp56/comment/j13redg/?utm_source=share&utm_medium=web2x&context=3)

**Comment by debugloop** [comment]
I'm not aware of it and I am a bit baffled as to how this happens. The key `<cr>` occurs in the default mappings, at least. As I can't reproduce it, please provide that minimal reproduction. Thanks in advance!

**Comment by gregorias** [comment]
Solved, it was caused by my personal setup.

To auto-close terminal upon detachment, I had

```lua
-- | Close terminals upon detachment.
function M.close_terminal_on_detach()
  vim.api.nvim_create_autocmd(
    { "TermClose" },
    {
      pattern = { '*' },
      command = [[call feedkeys('<cr>')]],
    })
end
```

telescope-undo was apparently using a terminal.

To fix the issue, I replaced my autocommand with https://github.com/neovim/neovim/issues/14986#issuecomment-902705190.

**Comment by debugloop** [comment]
Thanks for clearing that up. It's indeed using a terminal previewer if `delta` is configured and usable in order to render its color termcodes.
