### ISSUE TITLE
add new option: diff_context_lines?

### ISSUE THREAD

**Issue by emmanueltouzery** [debugloop/telescope-undo.nvim#12]
i'd rather not touch my neovim-wide `scrolloff`, but increasing this to non-zero really improves the display... so ideally i'd prefer if you could extend the extension options to add a new optional `diff_context_lines: number`...

If not possible, I guess I could `setlocal` the `scrolloff` before and after invoking telescope-undo but it's really a huge hack...

**Comment by debugloop** [comment]
Using `scrolloff` only is a holdover from when I hadn't figured out config yet, I'll implement this after the holidays. In the meantime you could `setlocal` in a `autocmd` for `FileType TelescopePrompt`, that's the Minimum Viable Hack I think.

**Comment by emmanueltouzery** [comment]
thank you! I tried
```lua
    vim.cmd('autocmd FileType TelescopePrompt setlocal scrolloff=3')
    vim.cmd('autocmd FileType TelescopeResults setlocal scrolloff=3')
```
but that didn't help. but no worries. i'll just fork & patch telescope-undo for the time being. maybe i even manage to make a PR for the new setting :)

**Comment by debugloop** [comment]
I just pushed an option for that, let me know if there are any issues 👍🏻
