### ISSUE TITLE
Bug: text-overflow/line-wrap not working properly in side-by-side view

### ISSUE THREAD

**Issue by joehannes** [debugloop/telescope-undo.nvim#17]
Hey!

Thx for your awesome plugin :-)

Here's a small UI-bug I just stumbled upon.
Not sure if it's a `telescope` or even `nvim` issue or even a `git-delta` issue,
but since I'm seeing this the first time right here in this plugin, I'm reporting it here.

![image](https://user-images.githubusercontent.com/63741107/210386107-beafeae5-3593-429e-b3e1-cca01b226f3a.png)

As you can see in the side-by-side view the wrapped lines follow up in the wrong column ... partially at least.

Cheers, Joehannes

**Comment by debugloop** [comment]
I just noticed this issue that I replied to in your comment on another issue. Here's the reply:

As for the wrapping issue, that's to be expected: The preview is a terminal output in case delta is used, and as such it behaves like one regarding color escape sequences and so on. No way around that except not using delta but the internal rendering with treesitter highlighting.

So I don't think there's anything I can do to handle this better, if the terminal output wraps, it'll look like this.
