### ISSUE TITLE
Can't restore or yank deletions

### ISSUE THREAD

**Issue by WilliamWelsh** [debugloop/telescope-undo.nvim#18]
- I can yank additions just fine
- When I attempt to yank deletions, it empties my register
- When I attempt to restore, it closes Telescope but the buffer doesn't change

I've tried moving around where the extension is loaded, tried your setup in your dotfiles, and made it print something random to make sure the keybinds are getting called, can't figure it out, here's my setup using `lazy.nvim`:

```lua
return {
	"nvim-telescope/telescope.nvim",
	dependencies = {
		"nvim-lua/plenary.nvim",
		"nvim-telescope/telescope-file-browser.nvim",
		"gbrlsnchs/telescope-lsp-handlers.nvim",
		"debugloop/telescope-undo.nvim",
	},
	lazy = false,
	config = function()
		local actions = require("telescope.actions")
		local builtin = require("telescope.builtin")

		vim.keymap.set("n", "<Leader>ff", function()
			builtin.find_files({
				no_ignore = false,
				hidden = true,
			})
		end)

		vim.keymap.set("n", "<Leader>fr", function()
			builtin.lsp_references()
		end)

		vim.keymap.set("n", ";f", function()
			builtin.find_files({
				no_ignore = false,
				hidden = true,
			})
		end)

		vim.keymap.set("n", "<Leader>fg", function()
			builtin.live_grep()
		end)

		vim.keymap.set("n", "<Leader>fb", function()
			builtin.buffers()
		end)

		vim.keymap.set("n", "<Leader>fj", function()
			builtin.jumplist()
		end)

		vim.keymap.set("n", "<Leader>fe", function()
			builtin.diagnostics()
		end)

		vim.keymap.set("n", "<Leader>fs", function()
			builtin.lsp_document_symbols()
		end)

		require("telescope").setup({
			defaults = {
				vimgrep_arguments = {
					"rg",
					"--color=never",
					"--no-heading",
					"--with-filename",
					"--line-number",
					"--column",
					"--smart-case",
				},
				prompt_prefix = "   ",
				selection_caret = "  ",
				entry_prefix = "  ",
				initial_mode = "insert",
				selection_strategy = "reset",
				sorting_strategy = "ascending",
				layout_strategy = "horizontal",
				layout_config = {
					horizontal = {
						prompt_position = "top",
						preview_width = 0.55,
						results_width = 0.8,
					},
					vertical = {
						mirror = false,
					},
					width = 0.87,
					height = 0.80,
					preview_cutoff = 120,
				},
				file_sorter = require("telescope.sorters").get_fuzzy_file,
				file_ignore_patterns = { "node_modules" },
				generic_sorter = require("telescope.sorters").get_generic_fuzzy_sorter,
				path_display = { "truncate" },
				winblend = 0,
				border = {},
				borderchars = { "─", "│", "─", "│", "╭", "╮", "╯", "╰" },
				color_devicons = true,
				set_env = {
					["COLORTERM"] = "truecolor",
				}, -- default = nil,
				file_previewer = require("telescope.previewers").vim_buffer_cat.new,
				grep_previewer = require("telescope.previewers").vim_buffer_vimgrep.new,
				qflist_previewer = require("telescope.previewers").vim_buffer_qflist.new,
				buffer_previewer_maker = require("telescope.previewers").buffer_previewer_maker,
				mappings = {
					n = {
						["q"] = actions.close,
					},
					i = {
						["<c-j>"] = actions.move_selection_next,
						["<c-k>"] = actions.move_selection_previous,
						["<esc>"] = actions.close,
					},
				},
			},
			extensions = {
				undo = {
					side_by_side = true,
					mappings = {
						i = {
							["<cr>"] = require("telescope-undo.actions").yank_additions,
							["<S-cr>"] = require("telescope-undo.actions").yank_deletions,
							["<C-cr>"] = require("telescope-undo.actions").restore,
						},
					},
				},
			},
		})

		require("telescope").load_extension("undo")
		vim.keymap.set("n", "<leader>u", "<cmd>Telescope undo<cr>")
	end,
}

```

**Comment by debugloop** [comment]
I suspect there might be interference from your terminal emulator. What do you use? Might that prevent receiving `<S-Cr>` and `<C-Cr>`? On the other hand, why would telescope receive a signal to close if `Cr` plus modifiers didn't make it through... I'm afraid I need more info to reproduce this. (@meijieru as well, assuming you have the same issue when Thumbing Up ;))

So ideally: I need to know your terminal emulator, your shell, and if you can reproduce it with less suspicious bindings than `Cr` with mods?

**Comment by maugusto99** [comment]
I have the same issue, restore doesn't work but yank deletions works just fine.

**Comment by maugusto99** [comment]
I have the same issue, restore doesn't work but yank deletions works just fine.
I mean telescope popup appears and close with the keybindings but nothing changes in the file.

Terminal: Alacritty
Shell: Fish
`return {
  'nvim-telescope/telescope.nvim',
  cond = function() return not vim.g.vscode end,
  config = function()
    local actions = require('telescope.actions')
    local action_layout = require("telescope.actions.layout")
    require("telescope").load_extension("fzf")
    require("telescope").load_extension("undo")
    require("telescope").setup {

      defaults = {
        prompt_prefix = "  ",
        selection_caret = " ",
        sorting_strategy = "ascending",
        layout_config = {
          height = 0.80,
          prompt_position = "top",
        },
        borderchars = {
          prompt = { "─", " ", " ", " ", "─", "─", " ", " " },
          results = { " " },
          preview = { " " },
        },
        mappings = {
          n = {
            ["<M-p>"] = action_layout.toggle_preview
          },

          i = {
            ["<C-j>"] = {
              actions.move_selection_next, type = "action",
              opts = { nowait = true, silent = true }
            },
            ["<C-k>"] = {
              actions.move_selection_previous, type = "action",
              opts = { nowait = true, silent = true }
            },
            ["<C-u>"] = false,
            ["<M-p>"] = action_layout.toggle_preview
          }
        }
      },

      pickers = {

        find_files = {
          find_command = { "fd", "--type", "f", "--no-ignore-vcs", "--strip-cwd-prefix" },
        },

        live_grep = {
          live_grep_command = { "rg" },
        },

        grep_string = {
          grep_string_command = { "rg" },
        }

      },

      extensions = {
        undo = {
          side_by_side = true,
          entry_format = "state #$ID, $STAT, $TIME",
          mappings = {
            i = {
              -- IMPORTANT: Note that telescope-undo must be available when telescope is configured if
              -- you want to replicate these defaults and use the following actions. This means
              -- installing as a dependency of telescope in it's `requirements` and loading this
              -- extension from there instead of having the separate plugin definition as outlined
              -- above.
              ["<cr>"] = require("telescope-undo.actions").yank_additions,
              ["<S-cr>"] = require("telescope-undo.actions").yank_deletions,
              ["<C-Cr>"] = require("telescope-undo.actions").restore,
            },
          },
        },
      }
    }
  end,
  keys = {
    { "<leader>:", "<cmd>Telescope command_history<cr>", desc = "Command History" },
    { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find Files" },
    { "<leader>fF", "<cmd>Telescope find_files hidden=true<cr>", desc = "Grep Project" },
    { "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "Find Hidden Files" },
    -- find
    { "<leader>fb", "<cmd>Telescope buffers<cr>", desc = "Buffers" },
    { "<leader>fr", "<cmd>Telescope oldfiles<cr>", desc = "Recent" },
    -- git
    { "<leader>gc", "<cmd>Telescope git_commits<CR>", desc = "commits" },
    { "<leader>gs", "<cmd>Telescope git_status<CR>", desc = "status" },
    -- search
    { "<leader>sb", "<cmd>Telescope current_buffer_fuzzy_find<cr>", desc = "Buffer" },
    { "<leader>sc", "<cmd>Telescope command_history<cr>", desc = "Command History" },
    { "<leader>sC", "<cmd>Telescope commands<cr>", desc = "Commands" },
    { "<leader>fd", "<cmd>Telescope lsp_definitions<cr>", desc = "Diagnostics" },
    { "<leader>sh", "<cmd>Telescope help_tags<cr>", desc = "Help Pages" },
    { "<leader>sH", "<cmd>Telescope highlights<cr>", desc = "Search Highlight Groups" },
    { "<leader>sk", "<cmd>Telescope keymaps<cr>", desc = "Key Maps" },
    { "<leader>sm", "<cmd>Telescope marks<cr>", desc = "Jump to Mark" },
    { "<leader>so", "<cmd>Telescope vim_options<cr>", desc = "Options" },
    { "<leader>ut", "<cmd>Telescope undo<cr>", desc = "UndoTree" },

  },
  dependencies = {
    'nvim-lua/plenary.nvim',
    {
      'nvim-telescope/telescope-fzf-native.nvim',
      build = 'make',
      cond = vim.fn.executable 'make' == 1,
    },
    "debugloop/telescope-undo.nvim",
  },
  cond = function() return not vim.g.vscode end,
}
`

**Comment by maugusto99** [comment]
I have the same issue, restore doesn't work but yank deletions works just fine.
I mean telescope popup appears and close with the keybindings but nothing changes in the file.

Terminal: Alacritty
Shell: Fish
```return {
  'nvim-telescope/telescope.nvim',
  cond = function() return not vim.g.vscode end,
  config = function()
    local actions = require('telescope.actions')
    local action_layout = require("telescope.actions.layout")
    require("telescope").load_extension("fzf")
    require("telescope").load_extension("undo")
    require("telescope").setup {

      defaults = {
        prompt_prefix = "  ",
        selection_caret = " ",
        sorting_strategy = "ascending",
        layout_config = {
          height = 0.80,
          prompt_position = "top",
        },
        borderchars = {
          prompt = { "─", " ", " ", " ", "─", "─", " ", " " },
          results = { " " },
          preview = { " " },
        },
        mappings = {
          n = {
            ["<M-p>"] = action_layout.toggle_preview
          },

          i = {
            ["<C-j>"] = {
              actions.move_selection_next, type = "action",
              opts = { nowait = true, silent = true }
            },
            ["<C-k>"] = {
              actions.move_selection_previous, type = "action",
              opts = { nowait = true, silent = true }
            },
            ["<C-u>"] = false,
            ["<M-p>"] = action_layout.toggle_preview
          }
        }
      },

      pickers = {

        find_files = {
          find_command = { "fd", "--type", "f", "--no-ignore-vcs", "--strip-cwd-prefix" },
        },

        live_grep = {
          live_grep_command = { "rg" },
        },

        grep_string = {
          grep_string_command = { "rg" },
        }

      },

      extensions = {
        undo = {
          side_by_side = true,
          entry_format = "state #$ID, $STAT, $TIME",
          mappings = {
            i = {
              -- IMPORTANT: Note that telescope-undo must be available when telescope is configured if
              -- you want to replicate these defaults and use the following actions. This means
              -- installing as a dependency of telescope in it's `requirements` and loading this
              -- extension from there instead of having the separate plugin definition as outlined
              -- above.
              ["<cr>"] = require("telescope-undo.actions").yank_additions,
              ["<S-cr>"] = require("telescope-undo.actions").yank_deletions,
              ["<C-Cr>"] = require("telescope-undo.actions").restore,
            },
          },
        },
      }
    }
  end,
  keys = {
    { "<leader>:", "<cmd>Telescope command_history<cr>", desc = "Command History" },
    { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find Files" },
    { "<leader>fF", "<cmd>Telescope find_files hidden=true<cr>", desc = "Grep Project" },
    { "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "Find Hidden Files" },
    -- find
    { "<leader>fb", "<cmd>Telescope buffers<cr>", desc = "Buffers" },
    { "<leader>fr", "<cmd>Telescope oldfiles<cr>", desc = "Recent" },
    -- git
    { "<leader>gc", "<cmd>Telescope git_commits<CR>", desc = "commits" },
    { "<leader>gs", "<cmd>Telescope git_status<CR>", desc = "status" },
    -- search
    { "<leader>sb", "<cmd>Telescope current_buffer_fuzzy_find<cr>", desc = "Buffer" },
    { "<leader>sc", "<cmd>Telescope command_history<cr>", desc = "Command History" },
    { "<leader>sC", "<cmd>Telescope commands<cr>", desc = "Commands" },
    { "<leader>fd", "<cmd>Telescope lsp_definitions<cr>", desc = "Diagnostics" },
    { "<leader>sh", "<cmd>Telescope help_tags<cr>", desc = "Help Pages" },
    { "<leader>sH", "<cmd>Telescope highlights<cr>", desc = "Search Highlight Groups" },
    { "<leader>sk", "<cmd>Telescope keymaps<cr>", desc = "Key Maps" },
    { "<leader>sm", "<cmd>Telescope marks<cr>", desc = "Jump to Mark" },
    { "<leader>so", "<cmd>Telescope vim_options<cr>", desc = "Options" },
    { "<leader>ut", "<cmd>Telescope undo<cr>", desc = "UndoTree" },

  },
  dependencies = {
    'nvim-lua/plenary.nvim',
    {
      'nvim-telescope/telescope-fzf-native.nvim',
      build = 'make',
      cond = vim.fn.executable 'make' == 1,
    },
    "debugloop/telescope-undo.nvim",
  },
  cond = function() return not vim.g.vscode end,
}```

**Comment by maugusto99** [comment]
I have the same issue with the restore command, but yank deletions works just fine
Terminal: Alacritty
Shell: Fish
```
return {
  'nvim-telescope/telescope.nvim',
  cond = function() return not vim.g.vscode end,
  config = function()
    local actions = require('telescope.actions')
    local action_layout = require("telescope.actions.layout")
    require("telescope").load_extension("fzf")
    require("telescope").load_extension("undo")
    require("telescope").setup {

      defaults = {
        prompt_prefix = "  ",
        selection_caret = " ",
        sorting_strategy = "ascending",
        layout_config = {
          height = 0.80,
          prompt_position = "top",
        },
        borderchars = {
          prompt = { "─", " ", " ", " ", "─", "─", " ", " " },
          results = { " " },
          preview = { " " },
        },
        mappings = {
          n = {
            ["<M-p>"] = action_layout.toggle_preview
          },

          i = {
            ["<C-j>"] = {
              actions.move_selection_next, type = "action",
              opts = { nowait = true, silent = true }
            },
            ["<C-k>"] = {
              actions.move_selection_previous, type = "action",
              opts = { nowait = true, silent = true }
            },
            ["<C-u>"] = false,
            ["<M-p>"] = action_layout.toggle_preview
          }
        }
      },

      pickers = {

        find_files = {
          find_command = { "fd", "--type", "f", "--no-ignore-vcs", "--strip-cwd-prefix" },
        },

        live_grep = {
          live_grep_command = { "rg" },
        },

        grep_string = {
          grep_string_command = { "rg" },
        }

      },

      extensions = {
        undo = {
          side_by_side = true,
          entry_format = "state #$ID, $STAT, $TIME",
          mappings = {
            i = {
              -- IMPORTANT: Note that telescope-undo must be available when telescope is configured if
              -- you want to replicate these defaults and use the following actions. This means
              -- installing as a dependency of telescope in it's `requirements` and loading this
              -- extension from there instead of having the separate plugin definition as outlined
              -- above.
              ["<cr>"] = require("telescope-undo.actions").yank_additions,
              ["<S-cr>"] = require("telescope-undo.actions").yank_deletions,
              ["<C-Cr>"] = require("telescope-undo.actions").restore,
            },
          },
        },
      }
    }
  end,
  keys = {
    { "<leader>:", "<cmd>Telescope command_history<cr>", desc = "Command History" },
    { "<leader>ff", "<cmd>Telescope find_files<cr>", desc = "Find Files" },
    { "<leader>fF", "<cmd>Telescope find_files hidden=true<cr>", desc = "Grep Project" },
    { "<leader>fg", "<cmd>Telescope live_grep<cr>", desc = "Find Hidden Files" },
    -- find
    { "<leader>fb", "<cmd>Telescope buffers<cr>", desc = "Buffers" },
    { "<leader>fr", "<cmd>Telescope oldfiles<cr>", desc = "Recent" },
    -- git
    { "<leader>gc", "<cmd>Telescope git_commits<CR>", desc = "commits" },
    { "<leader>gs", "<cmd>Telescope git_status<CR>", desc = "status" },
    -- search
    { "<leader>sb", "<cmd>Telescope current_buffer_fuzzy_find<cr>", desc = "Buffer" },
    { "<leader>sc", "<cmd>Telescope command_history<cr>", desc = "Command History" },
    { "<leader>sC", "<cmd>Telescope commands<cr>", desc = "Commands" },
    { "<leader>fd", "<cmd>Telescope lsp_definitions<cr>", desc = "Diagnostics" },
    { "<leader>sh", "<cmd>Telescope help_tags<cr>", desc = "Help Pages" },
    { "<leader>sH", "<cmd>Telescope highlights<cr>", desc = "Search Highlight Groups" },
    { "<leader>sk", "<cmd>Telescope keymaps<cr>", desc = "Key Maps" },
    { "<leader>sm", "<cmd>Telescope marks<cr>", desc = "Jump to Mark" },
    { "<leader>so", "<cmd>Telescope vim_options<cr>", desc = "Options" },
    { "<leader>ut", "<cmd>Telescope undo<cr>", desc = "UndoTree" },

  },
  dependencies = {
    'nvim-lua/plenary.nvim',
    {
      'nvim-telescope/telescope-fzf-native.nvim',
      build = 'make',
      cond = vim.fn.executable 'make' == 1,
    },
    "debugloop/telescope-undo.nvim",
  },
  cond = function() return not vim.g.vscode end,
}
```

**Comment by WilliamWelsh** [comment]
@maugusto99 Does yanking additions work for you? I can yank additions, but whenever I yank deletions it sets my register to be empty

**Comment by maugusto99** [comment]
@WilliamWelsh try another terminal. In kitty and wezterm works just fine but inside alacritty I have to explicity mark C-return to ReceiveChar for telescope restore state works.

**Comment by maugusto99** [comment]
@WilliamWelsh try another terminal. In kitty and wezterm works just fine but inside alacritty I have to explicity mark C-return to ReceiveChar for telescope restore state works.
As @debugloop said it must be a terminal problem.

**Comment by debugloop** [comment]
What mappings are you guys using now? As the `<cr>` based mappings are causing trouble for so many people, I'm looking to change (or rather: add) new defaults for insert and normal mode as well. But I'm kinda unsure on what to settle on. In normal mode, I'd probably go with `y` for yank additions, `Y` for deletions, and `u` for restore to that point. What are your ideas for insert mode?

**Comment by fecet** [comment]
As a curious beginner, most terminal cannot distinguish between <s-cr> <c-cr> and simple<cr>, I'm curious to know what terminal or shell you are using. Can you please share your preferred option?

**Comment by debugloop** [comment]
@fecet I use kitty + fish. I don't think that the shell really enters into the keybinding mess around `<cr>`, though.

**Comment by fecet** [comment]
I think so too. I have had a similar issue, but I'm not sure if it's because the terminal cannot distinguish between S-CR and CR by default, or if there are unexpected issues with key mappings related to CR. 
Just to confirm, in the default settings, the terminal doesn't know if the user pressed Shift+Enter or just Enter, and we can verify it from the output after pressing Ctrl+V followed by the key sequence right?

**Comment by kevinrobayna** [comment]
Same here i'm currently using kitty and I can't restore values enter just closes the view

https://github.com/kevinrobayna/dotfiles/blob/master/.config/nvim/lua/plugins/telescope.lua#L83

**Comment by WilliamWelsh** [comment]
The issue is not the keybinds, earlier I noted that I changed the keybinds to print something still printed. Yanking actually clears the register for me, so something is happening just not the right thing. Changing the keybinds to anything results in the same behavior

**Comment by Cruising0904** [comment]
same problem here I also use kitty no mapping for Enter for my terminal
require("telescope-undo.actions").restore command not works

**Comment by sethawright** [comment]
I followed this for my iterm config and it began working https://stackoverflow.com/questions/16359878/how-to-map-shift-enter

**Comment by tomlajtos** [comment]
> I followed this for my iterm config and it began working https://stackoverflow.com/questions/16359878/how-to-map-shift-enter

Thank you @sethawright , the info in the link worked for me as well. I use Kitty-Tmux-LazyVim.
In **kitty.conf** I added :
```
map shift+enter send_text all \x1b[13;2u
map ctrl+enter send_text all \x1b[13;5u
```
and in **tmux.conf** added these lines:
```
bind -n S-Enter send-keys Escape "[13;2u"
bind -n C-Enter send-keys Escape "[13;5u"
```

**Comment by debugloop** [comment]
Thanks for providing a definitive answer @sethawright ! Still open to potential alternative defaults that don't involve `<cr>`, but for now this seems the solution.
