### ISSUE TITLE
Requirements to see preview window?

### ISSUE THREAD

**Issue by femtomc** [debugloop/telescope-undo.nvim#20]
Hi!

I love the concept behind this package! I added it to my config:

```lua
	use({
		"nvim-telescope/telescope.nvim",
		requires = {
			"nvim-lua/plenary.nvim",
			"debugloop/telescope-undo.nvim",
		},
		config = function()
			require("telescope").setup({
				extensions = {
					undo = {
						use_delta = false,
						side_by_side = true,
						layout_strategy = "vertical",
						layout_config = {
							preview_height = 0.8,
						},
					},
				},
			})
			require("telescope").load_extension("undo")
		end,
	})
```

However, when I attempt to browse my undo tree -- I don't get a preview window:

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/34410036/212480391-1b6f76ff-6547-4bbd-bbf0-0ec98708f05f.png">

I do get a preview window when I use telescope for other things.

Is there some requirement to get a preview window which I might be missing?

**Comment by debugloop** [comment]
I can't check it out right now, but I'm pretty sure what happens is this: Your config states not to use `delta`, but to use `side_by_side`. However, regular diff can't do `side_by_side`, and I probably forgot to handle that combination of configs. I'll fix this soon and/or introduce a warning for it, but for now you'd need to get rid of the conflicting configs :)

**Comment by maugusto99** [comment]
@femtomc it maybe be your screen resolution, try to decrease your terminal font size. It works for me
