### ISSUE TITLE
Unable to change mappings

### ISSUE THREAD

**Issue by TxHawks** [debugloop/telescope-undo.nvim#22]
I want to map `<cr>` to `restore` instead of of `yank_additions` so have the following setup (with `lazy.nvim`):

```lua
return {
  {
    "telescope.nvim",
    opts = {
      defaults = {
        dynamic_preview_title = true,
        file_ignore_patterns = {
          "yarn.lock",
          "^./.git/",
        },
        vimgrep_arguments = {
          "rg",
          "--color=never",
          "--no-heading",
          "--with-filename",
          "--line-number",
          "--column",
          "--smart-case",
          "--hidden",
          "-g",
          "!.git/*",
        },
      },
      extensions = {
        fzf = {
          fuzzy = true,
          override_generic_sorter = true,
          override_file_sorter = true,
          case_mode = "smart_case",
        },
        undo = {
          use_delta = true,
          side_by_side = true,
          diff_context_lines = 15,
          mappings = {
            i = {
              ["<cr>"] = require("telescope-undo.actions").restore,
              ["<c-cr>"] = require("telescope-undo.actions").yank_additions,
              ["<S-cr>"] = require("telescope-undo.actions").yank_deletions,
            },
          },
        },
      },
      pickers = {
        buffers = {
          show_all_buffers = true,
          sort_lastused = true,
        },
        command_history = {
          theme = "ivy",
        },
        find_files = {
          hidden = true,
          fuzzy = true,
        },
        live_grep = {
          file_ignore_patterns = {
            "yarn.lock",
            "^./.git/",
            "pnpm-lock.yaml",
          },
        },
        lsp_code_actions = {
          theme = "cursor",
        },
        spell_suggest = {
          theme = "cursor",
        },
      },
    },
    dependencies = {
      {
        "debugloop/telescope-undo.nvim",
        config = function()
          require("telescope").load_extension("undo")
        end,
      },
    },
  },
}
```

But I get the following error:

```
   Error  17:20:13 notify.error lazy.nvim Failed to load `plugins.telescope`

~/.config/nvim/lua/plugins/telescope.lua:65: module 'telescope-undo.actions' not found:
```

What am I doing wrong here?

I thought that having `telescope-undo.nvim` in the `dependencies` loading the `undo` extension there should do the trick to allow me to change mappings.

**Comment by debugloop** [comment]
You'll have to move `require("telescope").load_extension("undo")` into your telescope config. To my knowledge, that is the only way. If you're aware of a telescope plugin that supports your style of doing it, please point me to it :)

**Comment by TxHawks** [comment]
Thanks, this works. However, mappings don't seem to change. I still have `<cr>` mapped to `yank_additions`.

Another problem, which I should probably open another issue for, is that non of the mapping seem to do what I expect (remapped or not). Can that be because I have `clipboard` set to `unnamedplus`?

**Comment by debugloop** [comment]
I have the same `clipboard` setting, so that should definitely work. It's basically determining the default register from your clipboard setting and using `vim.fn.setreg` with that. See `lua/telescope-undo/actions.lua`.

Regarding your mappings: Do you run `load_extension` after telescope's `setup` including the `extension.undo` config part? Because it won't be picked up otherwise. Again, I'm also not a fan of how telescope "centralizes" configuration of its plugins, but I've not been bothered by it enough to look into a different way of achieving it. Let me know if you do and what a telescope plugin can do to support that way of configuration for users :)

**Comment by TxHawks** [comment]
That was the issue - I had `load_extension` before the setup function. Thanks!

I wish there was an option to restore a specific set of changes rather than to a specific set of changes. That would be a killer feature in my opinion. But completely unrelated to this issue :)
