### ISSUE TITLE
can you give the packer installation code?

### ISSUE THREAD

**Issue by DonjiKong** [debugloop/telescope-undo.nvim#23]

**Comment by DonjiKong** [comment]
here is what I have right now:

use({
  "nvim-telescope/telescope.nvim",
  requires = {
    "nvim-lua/plenary.nvim",
    "debugloop/telescope-undo.nvim",
  },
  config = function()
    require("telescope").setup({
      extensions = {
        undo = {
          side_by_side = true,
          layout_strategy = "vertical",
          layout_config = {
            preview_height = 0.8,
          },
        },
      },
    })
    require("telescope").load_extension("undo")
    vim.keymap.set("n", "<leader>u", "<cmd>Telescope undo<cr>")
  end,
})


but the undo settings do not seem to be working. 

i think this must be happening because I do not have the packer code set up right

**Comment by debugloop** [comment]
Hi, sorry I won't read packers docs for you. From Telescope's point of view, you will have to ensure that:
1. both (telescope and telescope-undo) extensions are loaded
2. telescope is setup first, including the extension config
3. telescope-undo is added using `load_extension` last

Regarding your suggestion for keymaps, what are the defaults for undotree? I don't know it. I'm actually on the lookout for good default keymaps in insert mode. You could of course always map your desired keys yourself using the provided actions outlined in the README.
