### ISSUE TITLE
Don't print filename in preview

### ISSUE THREAD

**Issue by edshamis** [debugloop/telescope-undo.nvim#25]
Can you add an option to filter out the filename with it's frame from printing in preview?

**Comment by debugloop** [comment]
Sorry I can not. This is generated by the diff utility (whatever you're using). You can configure delta for instance to omit the file name header, but I am not aware on how to do that conditionally (i.e. only in telescope-undo). I'm open to include a simple "truncate first n lines" kind of option that works regardless of diff tool with a default of 0. If that line annoys you enough to go for it yourself I'll be happy to give you some pointers to get your PR started :)

**Comment by meisocafe** [comment]
I know the issue is marked as completed, but I would like to provide a working solution for anybody who stumbles on this. You can use the custom command to pass specific options to delta like this:

```lua
undo = {
	use_delta = false,
	use_custom_command = { "bash", "-c", "echo '$DIFF' | delta --file-style omit" },
	diff_context_lines = 13,
	layout_strategy = "flex",
}
```
