### ISSUE TITLE
No preview window

### ISSUE THREAD

**Issue by silentjay** [debugloop/telescope-undo.nvim#27]
When I open the plugin no preview window is shown.

![image](https://user-images.githubusercontent.com/3902481/234824811-0ed6b0cb-fc30-46f4-bd55-da9e3027b5f0.png)

My config is as follows:

```
  {
    "nvim-telescope/telescope.nvim",
    dependencies = {
      { "nvim-lua/plenary.nvim" },
      {
        "debugloop/telescope-undo.nvim",
        config = function(plugin, opts)
          require "plugins.configs.telescope" (plugin, opts) -- include the default astronvim config that calls the setup call
          local telescope = require "telescope"
          telescope.setup {
            pickers = { oldfiles = { cwd_only = true } }, -- only show files in current directory
            extensions = {
              undo = {
                use_delta = true,
                side_by_side = true,
                layout_strategy = "vertical",
                layout_config = {
                  preview_height = 0.8,
                },
              },
            },
          }
          telescope.load_extension "undo"
        end,
      },
    },
    keys = {
      { "<leader>fu", "<cmd>Telescope undo<cr>", desc = "Open File Undo His. in Telescope" },
    },
  },
```
Not sure if this is how I've had to integrate the plugin with astronvim's telescope integration. However changing `layout_strategy` to `horizontal` works as expected and the preview window is shown.

**Comment by beyond-fu** [comment]
If you want the preview result just like in README, use `horizontal` rather than `vertical`. Maybe it's the author's negligence in the configuratiojn part of README.

**Comment by debugloop** [comment]
Hi, pretty sure the issue was unrelated to the plugin. If your notification in the screen shot is any indication, you config tried to attach a LSP client to the preview buffer, failed, and closed the window? I can only guess if that is indeed the reason, but feel free to reopen with more info if you want to get to the bottom of this.
