### ISSUE TITLE
Allow having a different telescope layout for this extension than the default

### ISSUE THREAD

**Issue by chrisgrieser** [debugloop/telescope-undo.nvim#3]
(continuing #1 )
>  If you find that this extension doesn't respect telescope-wide settings please reopen with an example 👍🏻

Probably didn't explain it properly in the previous issue: the issue is not that telescope-configs are not respected, but rather that this extension cannot have a configs that *differ* from the default telescope config.

With telescope, we are able to configure every picker individually, spell suggestion can have a different layout from file opener. Buffer selection can start in normal mode, while file opener can start in insert mode, etc.

Especially for this undo tree picker, it would make much sense to have the same kind of configurability. For example due to the diff views, it would make sense to have a wider preview window etc.

**Comment by debugloop** [comment]
I don't think I'm dropping options. For instance, the following works fine for me since my config implementation:

```lua
extensions = {
  undo = {
    layout_strategy = "vertical",
    layout_config = {
      preview_height = 0.8,
    },
  },
},
```

But I just realized that my comment on #1 didn't make that too clear... Or are we still talking past one another? :) Next up is side-by-side config for the preview diff.

**Comment by chrisgrieser** [comment]
ah yes, that works now! (wasn't working in a previous version, apparently.)
