### ISSUE TITLE
Bug: Instead of re-using scrolloff, let's have an specific option

### ISSUE THREAD

**Issue by Zeioth** [debugloop/telescope-undo.nvim#31]
People often use high values for scrolloff to keep the mouse in the midle of the screen. This provoke telescope-undo.nvim to always show the first line of the buffer.

There is really no reason to re-use this option instead of having our own.

**Comment by debugloop** [comment]
See the config value `diff_context_lines` as shown in the README, `scrolloff` is just the default.
