### ISSUE TITLE
Bug: Preview show "[Process exited 0]" when delta is used

### ISSUE THREAD

**Issue by Zeioth** [debugloop/telescope-undo.nvim#32]
On linux
![screenshot_2023-06-05_02-39-30_650523552](https://github.com/debugloop/telescope-undo.nvim/assets/3357792/67baf763-a239-4e78-b548-a5763a345467)

EDIT: I see `previewers.new_termopen_previewer` is a Telescope method, so I should probably report it [there](https://github.com/nvim-telescope/telescope.nvim/issues/605).

**Comment by debugloop** [comment]
Your EDIT is entirely correct, nothing I can do about this message from my end 🙃

**Comment by medwatt** [comment]
I came across this issue. Is there a solution for it?

**Comment by debugloop** [comment]
Hi, there is no "fix" for this. Feel free to read up on it at the [issue created by OP](https://github.com/nvim-telescope/telescope.nvim/issues/605), which concerns the API I am using.

As far as I can tell that issue only contains hacky fixes which involve stripping the last line or similar. I am not willing to implement those just for aesthetics, others might consider the line useful: It is proof that delta ran successfully and no lingering terminal is running in the background. Further, this message actually comes from the underlying `:term` command used by the Telescope API which I in turn use here. You can try it  out yourself by running `:term echo` for instance.

Feel free to create an issue with Telescope, as anything I could do would basically patch their API response anyhow. If they respond similarly, you could decide to take it up in a Neovim issue. However, I hardly think they'll consider it: This would be a breaking change for plugins and scripts which might depend on that line being there.

**Comment by debugloop** [comment]
I haven't tried it myself, but you would do the same as the commenters there: Set the previewer in the opts and Telescope should pick it up correctly. You can copy the previewer used by telescope-undo as a base and implement their changes on top or go for theirs entirely at first 👍🏻
