### ISSUE TITLE
Add support for telescope theme

### ISSUE THREAD

**Issue by WatcherWhale** [debugloop/telescope-undo.nvim#33]
It would be nice to also support the use of telescope themes

**Comment by bartopine** [comment]
i second this 👍

**Comment by debugloop** [comment]
Hi, I'm not entirely sure what telescope-undo does not support. Can you give me an example? To my knowledge, all config options are respected.

**Comment by bartopine** [comment]
Hello!

Below is the screenshot of what we meant. Take for example the extension file browser below has the theme set to "ivy". The Ui appears like that.
But if you set the theme of Undo to "ivy". It will still look like the default theme.

Telescope File-Browser theme set to "ivy"
![file browser](https://github.com/debugloop/telescope-undo.nvim/assets/125934754/28382a58-fc25-4577-8135-56f16ecdcbbd)

Telescope Undo theme set to "ivy"
![undo](https://github.com/debugloop/telescope-undo.nvim/assets/125934754/72d97f5e-cbea-42ab-9002-89f8f2f17b4a)

**Comment by debugloop** [comment]
TIL about the literal `theme` key, thanks! I've added support for that, hope it works for you 👍🏻
