### ISSUE TITLE
Add an option to merge yank_addition and yank_deletion

### ISSUE THREAD

**Issue by Twix53791** [debugloop/telescope-undo.nvim#34]
Hi,
Thanks for this plugin, a bit confusing to use for me, but its good to have it, just in case to recover a lost piece of code in the undo tree...

I think however than having to key bindings to yank according to addition/deletion state is 
1) complicate
2) prone to unwanted behaviors :naming create an empty register if I press <CR> on a deletion...

So I propose to just add an option to merge the two commands : it will detects if the item is a deletion or addition and yank accordingly. It is not a problem in any case : we just yank something to the register, it can be bad! And it will avoid the possibility of empty register entries.

I am just suggesting this change. As I am just setting up my vim config, I am not going to dif the code and send a pull request. Maybe oneday if nothing hcange and I use this plugin a lot...

If anyone listen my advice and change that, thank you by advance!

**Comment by debugloop** [comment]
If I understand you correctly you want something like following, yes?

```lua
-- make sure telescope is loaded first, i.e. without telescope-undo
require("telescope").setup({...your basic condfig...})

-- during loading of telescope-undo, use the following
local function yank_larger()
  entry = require("telescope.actions.state").get_selected_entry()
  if entry ~= nil then
    if #entry.value.additions > #entry.value.deletions then
      return require("telescope-undo.actions").yank_additions()
    else
      return require("telescope-undo.actions").yank_deletions()
    end
  end
end

require("telescope").setup({
  extensions = {
    undo = {
      -- ... other telescope-undo config
      mappings = {
        i = {
          ["<cr>"] = yank_larger,
          ["<S-cr>"] = false,
        },
      },
    },
  },
})
```

As outlined in the snipped, you'll have to load telescope before configuring telescope-undo for this custom action. But lazy will do that for you for instance (stick both in separate specs, put the two halves into the `config` function, depend on telescope from telescope-undo).

I agree, this would be nice to have as a default action and I'll include it soon, but please go ahead, test above code and let me know if that's what you expect 👍🏻

**Comment by debugloop** [comment]
This is now supported with a builtin action not mapped by default.
