### ISSUE TITLE
Incompatibility with Zellij

### ISSUE THREAD

**Issue by badrbouslikhin** [debugloop/telescope-undo.nvim#35]
I've encountered a compatibility issue between this plugin and [Zellij](https://zellij.dev/), the terminal multiplexer. Pressing <C-cr> doesn't revert to a previous state.

Is there any known workaround?

Thanks!

**Comment by debugloop** [comment]
You could always change the mapping around and see what works through Zellij's escaping. I expect that you'll find another mapping than the default working fine, but I'm afraid there'll be no workaround preserving the default mappings. I'm open to additional default mappings though, let me know if you find a ergonomic/mnemonic solution and I'll include it. Especially `<Cr>` has caused trouble before...
