### ISSUE TITLE
Does not work with page and neovim remote

### ISSUE THREAD

**Issue by kevintraver** [debugloop/telescope-undo.nvim#36]
Does not work when PAGER is set to use [page](https://github.com/I60R/page) (which uses [neovim-remote](https://github.com/mhinz/neovim-remote))

The **telescope-undo** window shows a save prompt, and then **page** throws a panic error:

```thread thread 'main' panicked at 'Cannot create buffer: NeovimError (Some (0)```

**Comment by kevintraver** [comment]
Running `delta` with `page` works just fine.

So it seems to be an issue with spawning inside the telescope window.

https://github.com/I60R/page/issues/44

**Comment by debugloop** [comment]
Alright, I'll close this for now and trust in an upstream fix. Please reopen or tag me if the outcome of above issue requires changes on my part 👍🏻
