### ISSUE TITLE
delta in wsl not working

### ISSUE THREAD

**Issue by stormherz** [debugloop/telescope-undo.nvim#44]
Hi!

First of all, thanks for the plugin.

I'm having issues with trying to use it with delta inside WSL. I've looked into the code and discovered `if opts.use_delta and not is_wsl` which lead me to #14, but I'm not sure why this restriction took place. While working in WSL with delta installed within it should be exactly the same workflow as if we were running via any other linux shell. 

Is this restriction still relevant?

PS: it actually works fine, I've removed `is_wsl` check and reordered if/elseif branches to use bash right away and it works as expected, not sure if I want to use delta now (a bit too noisy for me), but the initial question stands.

**Comment by debugloop** [comment]
Hi, no idea if it's still relevant. I've never used WSL or set up nvim on Windows, so I have no clue whatsoever.

Happy to remove the restriction if your assessment is that having it try to run delta makes WSL folks more happy than just barring them from using it 👍🏻

**Comment by stormherz** [comment]
I'm actually not sure if it's fine to remove it right now, since I'm running nvim inside WSL, so it's "linux all the way", but I can imagine it might be quite different scenario if nvim was launched in windows and tried to use delta, that's probably the reason why there's WSL check in the first place. Anyway, I'm not confident in dropping that restriction, so it's better leave it that way, maybe someone will find this issue later on and work it out for both win/linux.

I'm closing this one, sorry for taking your time =) And thanks again for the plugin!

**Comment by TSoli** [comment]
This is probably what I experienced [here](https://github.com/debugloop/telescope-undo.nvim/issues/30#issuecomment-1611005397)

**Comment by tfriedel** [comment]
just had this issue as well. I forked this plugin and removed it there. Works fine.
If nvim was launched in windows, but not wsl, then the check for wsl would not be relevant.
I propose to remove the restriction!
