### ISSUE TITLE
Error executing lua [string ":lua"]:1: ...

### ISSUE THREAD

**Issue by Aaronik** [debugloop/telescope-undo.nvim#5]
Hello,

I'm very excited about this plugin, but I cannot get it to work.

I've installed it using Plug, is that a viable means?

It is installed after telescope.

Here is the error I'm getting:

```vim
E5108: Error executing lua [string ":lua"]:1: attempt to call a table value
stack traceback:
        [string ":lua"]:1: in main chunk
```

This happens when I call `:lua require('telescope-undo')()`.

Also, `Telescope undo` results in another error, `[telescope.run_command]: Unknown command`

Is it somehow not picking up my telescope install? Do I need to make the switch to packer or something?

`:checkhealth telescope` results in

```vim
   
telescope: require("telescope.health").check()    
========================================================================    
## Checking for required plugins    
  - OK: plenary installed.    
  - WARNING: nvim-treesitter not found.     
    
## Checking external dependencies    
  - OK: rg: found ripgrep 13.0.0    
  - WARNING: fd: not found. Install sharkdp/fd for extended capabilities    
    
## ===== Installed extensions =====
```

with notably no installed extensions, although I use telescope regularly, and have other plugins that sit on that window like ChatGPT working just fine. I'm not super well versed in this stuff so I don't know if that's even a correct analysis, sorry in advance for my noobishness.

**Comment by debugloop** [comment]
Sorry, the README contained some outdated info: I've prepared to add more functions to this module, so you won't be able to call the module directly anymore: `:lua require('telescope-undo').undo()` is the correct invocation, with `opts` as parameter if you wish.

As for `:Telescope undo`, I suspect you did not include the line about loading the extension (`require("telescope").load_extension("undo")`) in your install.

Let me know if you're still having trouble :+1:
