### ISSUE TITLE
Diff View output is wrong

### ISSUE THREAD

**Issue by alewis001** [debugloop/telescope-undo.nvim#50]
The diff appears to wrong in the following scenario.

# Steps
1. Open new buffer
2. Type:
    1. `i`
    2. `a<cr>`
    3. `b<cr>`
    4. `c<cr>`
    5. `d<cr>`
    6. `esc`
3. Move up one line (to line 3), then `dd`
4. Move up one line (to line 2), then:
    1. `o`
    2. `X`
    3. `esc`
 5. Open Telescope Undo.

The initial state was:
```
a
b
c
d
```

The final contents of the buffer is:
```
a
b
X
d
```

The output of the diff for the last/latest state shows: 
```
a
+X
b
d
```

Which is wrong (I think). Shouldn't it be the following instead?
```
a
b
+X
d
```

**Comment by debugloop** [comment]
Hi, unbelievable no one noticed this until now. Can you try `fix-context-calculation-error` and let me know if everythings works as expected? It's a tiny error but a major change in the way we calculate diffs. You can override your lazy spec by including `branch = "fix-context-calculation-error",`.

**Comment by alewis001** [comment]
Sure, will test as soon as I can but it might be a day or so before I can get to it. I will try to get to it as soon as I can (I was on holiday last week).

**Comment by alewis001** [comment]
The change does appear to fix the issue but I do have one thing I noticed but it might be a matter of opinion. In the example above, if instead of writing abcd in one go and did an `esc` and then `o` for each character, when viewing the undo stack the last line always appears as being removed and then added again. 

I assume this is due to the addition of the line ending and could be arguably considered the accurate representation. The only reason I mention it is that it jumped out at me, and when I compared it to effectively the same scenario using Git, Git represented just the additional line and didn't consider the addition of the line ending as a modification. I checked my Git config and I don't appear to have made any settings that would affect that behaviour.

E.g. In telescope undo...
![Screenshot 2024-04-30 at 14 43 54](https://github.com/debugloop/telescope-undo.nvim/assets/3482446/eb91ede4-630a-4ed5-a77b-3e15ffe628ce)

In Git (the screenshot is lazygit but the same diff can be seen in `git log -p`)
![Screenshot 2024-04-30 at 14 44 39](https://github.com/debugloop/telescope-undo.nvim/assets/3482446/8a3d7aad-a340-4965-bf40-bba3cb88850a)

**Comment by debugloop** [comment]
Yeah there's a lot of possibility where the difference comes from. You could have configured your git or your lazygit to ignore whitespace in a diff, which would pass the diff to delta without the whitespace. I'll have a look if I can make `vim.diff` do the same, should be trivial to add if that is the case. If not, you're out of luck as I'm not willing to tinker with the diff myself and somehow divine whether part of a change is whitespace ;)

**Comment by debugloop** [comment]
I checked, it's possible and I'll make it configurable. You're however aware that this can lead to completely empty previews of undo states that added whitespace, yes?

**Comment by alewis001** [comment]
> You could have configured your git or your lazygit to ignore whitespace in a diff, which would pass the diff to delta without the whitespace.

I haven't (AFAICT) but that's besides the point, what Git is doing is specific to Git and may not be right or what people expect from Neovim so I totally agree with your stance on not tinkering with whatever (neo)vim is generating :)

> I checked, it's possible and I'll make it configurable

Making it configurable is a step further than I expected :) and personally I'll take whatever (Neo)vim picked as the intended behaviour.

As I mentioned, it was just behaviour I noticed and thought I'd mention it in case it was something you were or were not expecting. It was mainly because you mentioned _"it's a tiny error but a major change in the way we calculate diffs."_ so I wondered whether it may have been something that might have been part of the major change and thought I may as well mention it just in case.

Thanks for all the work, and great plugin btw!!

**Comment by debugloop** [comment]
This is now configurable on `main` :)
