### ISSUE TITLE
Clear undo history

### ISSUE THREAD

**Issue by gldtn** [debugloop/telescope-undo.nvim#52]
Is it currently possible clear history or delete a specific state? For example over time the undo history becomes very large and I know I won't need it anymore, so it would be nice to at least manually delete older state. Currently I have saved_only turn on to keep it somewhat getting out of control.

Thanks!

**Comment by debugloop** [comment]
Hi, we're just using the built-in methods for managing undo state. As such, you can use any of the methods floating around the Internet, such as https://vi.stackexchange.com/a/16915. I'm actually not aware of any way to delete a specific state, everything I ever saw was relying on limiting the length and having nvim truncate the undolist by itself (as the link recommends).

As plugin, I have no intention to delete anything from nvim internal state. Someone would turn out to be surprised by that behaviour and lose something important, probably :)
