### ISSUE TITLE
`Vim(undo):E438: u_undo: line numbers wrong` on a few files

### ISSUE THREAD

**Issue by joaomendoncaa** [debugloop/telescope-undo.nvim#59]
I can't seem to figure out why, but there's a few buffers where `telescope.extensions.undo.undo()` breaks in this manner (also blows up when I try to literally undo):

![image](https://github.com/user-attachments/assets/ec79441f-4605-4d1d-9898-c1492148b561)

I already tried to clear the affected file's history with `:e!` (since I suspect this is some kind of corruption) but nothing worked. I also can't find the undo files persisting the history.

> ⚠️  Keep in mind it's all working as intended, it's just that a few buffers (rarely) blow up as shown above.

If anyone has any clue on the origin of the problem, I'd appreciate some insights. Thank you.

**Comment by debugloop** [comment]
That's an error from Neovim's undo feature. You'll see the same if you spam `u` for long enough. There's nothing the plugin can do about it, but you'll have to get rid of your persisted undo. Check `:set undofile` and `:set undodir` to see what you've set it too and where it is being persisted from 👍🏻
