### ISSUE TITLE
Making bindings configurable

### ISSUE THREAD

**Issue by fbearoff** [debugloop/telescope-undo.nvim#6]
The `<C-CR>` key sequence does not work in some terminals, the bindings for restore, yank deletions, and yank additions should be user configurable.

Also, the descriptions in telescope whichkey (<C-_> in insert mode, ? in normal) show <anonymous> as the action name instead of the mapped action.

**Comment by debugloop** [comment]
It is possible to remap keys now. I haven't gotten the telescope whichkey (TIL, didn't know about that at all) to work though. Can you point me to an extension that gets this right?

Also: Remapping the action now changes how this should be installed, as this extensions actions need to be available when telescope's `setup` is called. I.e. the requirements need to be the other way around, as outlined in the README now. I don't quite like it, is that how this key remapping normally works?

**Comment by fbearoff** [comment]
[Neoclip](https://github.com/AckslD/nvim-neoclip.lua) shows bindings in the whichkey prompt for a few actions (paste, paste_behind, etc.).
