### ISSUE TITLE
Bug: `side_by_side` is ignored

### ISSUE THREAD

**Issue by chrisgrieser** [debugloop/telescope-undo.nvim#8]
```lua
extensions = {
		undo = {
			side_by_side = false,
		},
	},
```

and yet, i still get a side-by-side view?
<img width="1461" alt="Pasted image 2022-12-20 16 26 06" src="https://user-images.githubusercontent.com/73286100/208703110-a0075431-1ddf-444c-8c03-4f040b1b065c.png">

**Comment by debugloop** [comment]
I can't reproduce this, can you confirm there's no error on your end (not reloaded, overwritten somewhere, delta diffs without side-by-side on cli, ...)

![20221220_16h42m20s_grim](https://user-images.githubusercontent.com/4604331/208709005-8ea84c82-912d-4f52-be74-de2b2d1d21eb.png)

**Comment by chrisgrieser** [comment]
ah yes, I had side by side set to true in my git config, that was it. (Might wanna add this info to the readme though.)

**Comment by TSoli** [comment]
> ah yes, I had side by side set to true in my git config, that was it. (Might wanna add this info to the readme though.)

I would argue this is a bug actually since it can override the git config if the git config has `side_by_side` set to `false` but cannot override side_by_side to be `false` if it is `true` in the git config.

**Comment by debugloop** [comment]
Well if it is I'm afraid you'd have to take it up with `delta`: This plugin just provides a `-s` (i.e. use side by side) to the `delta` binary if configured to do so. There is no CLI flag on `delta` to specify "do not use side by side" that I could pass when our config is set to false.

**Comment by TSoli** [comment]
Ah I see, thanks for clarifying!
