### ISSUE TITLE
Minor FR: abbreviate list of items

### ISSUE THREAD

**Issue by chrisgrieser** [debugloop/telescope-undo.nvim#9]
Especially with a horizontal layout on a smaller screen, these do cost quite a bit of space. to save space, one could:
- remove the word "state", it's redundant
- remove "ago" 
- remove zero diff counts (`+0` and `-0`)
- abbreviate "minutes" to "min", etc.
- abbreviate "just now" to "now"

<img width="653" alt="Pasted image 2022-12-20 16 26 43" src="https://user-images.githubusercontent.com/73286100/208703254-ab21eab3-99cd-4a87-8908-4db1fce59147.png">

**Comment by chrisgrieser** [comment]
also, the `filename → filename` is probably also irrelevant in the context of vim
<img width="1488" alt="Pasted image 2022-12-20 20 22 42" src="https://user-images.githubusercontent.com/73286100/208749656-d3598be8-9ebb-4569-a8e8-7ae99f6e7785.png">

**Comment by debugloop** [comment]
I think I ideally wanna address this as some sort of format string option, but I have to think a bit on how. Maybe a `minimal` bool will do too. Your trims are a bit to radical to my liking, but I realize the value for small terminals.

Some more thoughts:
* time expressions come from a library I had hoped to un-vendor at some point
* hiding zero diff counts will mess with the alignment
* regarding alignment, I was thinking of replacing the list with a table already

Regarding the filename suggestion, that's what gives `delta` the ability to apply syntax highlighting. To share some of the process how I arrived at https://github.com/debugloop/telescope-undo.nvim/commit/4763a5e1e4f4139f66ebfe1adbb7e3b8d7737538: Specifying a CLI option from `vim.bo.ft` and passing it to `delta` does not work, as `delta` apparently doesn't like to highlight diffs it formats. We probably could have `delta` do the actual diffing though, but that would mean messing with temporary files.

**Comment by debugloop** [comment]
I've just pushed a config option that allows some of your suggestions: you can remove `state #`, and diffstat is now hiding zero values. I've decided not to mess with the strings provided by the time formatting library as I still hope to include this luarock into the plugin without vendoring it somehow. Hope that works for you 👍🏻

**Comment by chrisgrieser** [comment]
yeah, that does work as well. Thanks for the implementation! `entry_format = "$STAT: $TIME"` totally works for me 🙂
<img width="1414" alt="Pasted image 2022-12-28 17 03 21" src="https://user-images.githubusercontent.com/73286100/209839638-45e1e735-4293-46ef-af19-41932c470b72.png">
